### ISSUE TITLE
Re2 issue

### ISSUE THREAD

**Issue by michalss** [Ekey/REE.PAK.Tool#1]
Hi, can you please checkout the new filenames for RE2 PC release? Latest update completely renamed all essential files. We are interested especially in .msg files. Normally small change in last number is present (.msg.14 to some other number at the end) and we can do some guessing (algorithmically), but this time it is not the case (we tested numbers from 0 to 1000000).  It will be probably the same extension for all msg files so we can use previous list. Thanks in advance.

**Comment by Ekey** [comment]
[This](https://residentevilmodding.boards.net/thread/16547/information-format-changes-tracing-patch) will help you.
