### ISSUE TITLE
 Hi It is not visible in which folder the msg 16 files are

### ISSUE THREAD

**Issue by sinnerclown380** [Ekey/REE.PAK.Tool#10]
Hello, can you update the file list of Ghosts 'n Goblins Resurrection game, please, the msg 16 translation files are not visible in which folder.thanks

**Comment by sinnerclown380** [comment]
Can you share your discord address?

**Comment by Ekey** [comment]
You can find me in [Modding Haven](https://discord.gg/moddinghaven) discord.
