### ISSUE TITLE
Ghost trick font

### ISSUE THREAD

**Issue by dangvh5** [Ekey/REE.PAK.Tool#11]
Hi, currently Im using REE.FontCryptor.exe to decript a oft.1 file into .ttf, but I can not convert it back to oft.1. Other font files are converted perfectly. Here the zip of that file.
[df-sougei-w7.zip](https://github.com/Ekey/REE.PAK.Tool/files/12358872/df-sougei-w7.zip)

**Comment by Ekey** [comment]
Hi. This file has a different font type. I added it, but there is no guarantee that the game will work with it :)
