### ISSUE TITLE
Resident Evil 4 & Separate Ways

### ISSUE THREAD

**Issue by Alkimical** [Ekey/REE.PAK.Tool#12]
Resident Evil 4 with Separate Ways files names will be released?

**Comment by Ekey** [comment]
Nope, cuz i don't have this game.

**Comment by Ekey** [comment]
> > Nope, cuz i don't have this game.
> 
> Hey, I have this game and DLC on PC (Steam) and PS4 (Jailbreak and owned digital content), also RE Village Full game too

Hi, For PC RE4 and DLC the list is already exists.

> 
> Do you have a discord? So we can talk and also need to make release list from all this too

`Ekey#8012`
