### ISSUE TITLE
How to use REE.FontsCryptor to decrypt?

### ISSUE THREAD

**Issue by cnnhean** [Ekey/REE.PAK.Tool#13]
Sorry for the noob question, but after building, how can i use it to decrypt the oft.1 file?

I've only been able to found this batch for crypting 
`@ECHO OFF
:TOP

IF (%1) == () GOTO END
REE.FontsCryptor %1 %~n1".oft.1"

SHIFT
GOTO TOP

:END`

And after decrypting, how can i edit/view/convert the oft file?

Thank you.

**Comment by Ekey** [comment]
The output file is the default TrueType Windows font file. You can use any Font Editor

**Comment by cnnhean** [comment]
Thank you so much for the reply, i tried it, but it didn't seem to work for me, can you help me with the batch file?

**Comment by Ekey** [comment]
Example for decrypt

```
@echo off
color a
REE.FontsCryptor eurostilenextpro-nr.oft.1 eurostilenextpro-nr.ttf
pause
```

Example for encrypt

```
@echo off
color a
REE.FontsCryptor eurostilenextpro-nr.ttf eurostilenextpro-nr.oft.1
pause
```
