### ISSUE TITLE
RE8 Mac?

### ISSUE THREAD

**Issue by Ferbez** [Ekey/REE.PAK.Tool#14]
Tried to extract .pak files from macOS port of RE8, but looks like file paths are different - existing list for PC doesn’t help. Is there a way to discover file paths for macOS version?

**Comment by Ekey** [comment]
Well I don't have the Mac version of this game. If you can upload it for me we can make a list ;)

**Comment by Ferbez** [comment]
I've bought it on App Store and not sure how to properly share it. Here's a [link](https://ygkz-my.sharepoint.com/:f:/g/personal/48_ygkz_onmicrosoft_com/EvchOwjHqMJOt7veGNLz-2oBJyUAsKpga7HooYw0X135Cg?e=9pIr2d) though. Send me a notice and I'll delete it once you're ready

**Comment by Ekey** [comment]
Done. List for MacOS > [RE8_MAC_Release](../tree/main/Projects)
