### ISSUE TITLE
REE.FontsCryptor ，ree pak too

### ISSUE THREAD

**Issue by xjgames** [Ekey/REE.PAK.Tool#16]
I am not a programmer
Can you send an executable file?

**Comment by Ekey** [comment]
[REE.PAK.Tool.zip](https://github.com/Ekey/REE.PAK.Tool/files/13773356/REE.PAK.Tool.zip)

**Comment by xjgames** [comment]
> [REE.PAK.工具.zip](https://github.com/Ekey/REE.PAK.Tool/files/13773356/REE.PAK.Tool.zip)

Thank you for your help

**Comment by xjgames** [comment]
> [REE.PAK.Tool.zip](https://github.com/Ekey/REE.PAK.Tool/files/13773356/REE.PAK.Tool.zip)

Sorry, I don't know how to write code
Can you provide the bat file

**Comment by Ekey** [comment]
Example usage:

**REE.Unpacker**
```
@echo off
color a
REE.Unpacker RE4_PC_Release "f:\Games\RE4\re_chunk_000.pak" "f:\Games\RE4\re_chunk_000"
pause
```

**REE.FontsCryptor**

```
@echo off
color a
REE.FontsCryptor "f:\Games\RE4\re_chunk_000\natives\stm\_chainsaw\ui\ui0000\font\capcom-dotgothic12std-m.oft.1" "f:\Games\RE4\re_chunk_000\natives\stm\_chainsaw\ui\ui0000\font\capcom-dotgothic12std-m.oft.1.dec"
pause
```

**Comment by xjgames** [comment]
> 用法示例：
> 
> **REE 解包器**
> 
> ```
> @echo off
> color a
> REE.Unpacker RE4_PC_Release "f:\Games\RE4\re_chunk_000.pak" "f:\Games\RE4\re_chunk_000"
> pause
> ```
> 
> **REE.FontsCryptor**
> 
> ```
> @echo off
> color a
> REE.FontsCryptor "f:\Games\RE4\re_chunk_000\natives\stm\_chainsaw\ui\ui0000\font\capcom-dotgothic12std-m.oft.1" "f:\Games\RE4\re_chunk_000\natives\stm\_chainsaw\ui\ui0000\font\capcom-dotgothic12std-m.oft.1.dec"
> pause
> ```

Thank you very much
