### ISSUE TITLE
Where do I enter cmd?

### ISSUE THREAD

**Issue by Kazserah** [Ekey/REE.PAK.Tool#20]
Sorry I'm not that familiar with this sort of thing, I've used REtool to extract some pak files but that's it.

where am I supposed to use those commands? For example: REE.Unpacker "RE8_M_PS5_Demo.list" "re_chunk_000.pak"

I've tried opening a powershell and cmd window inside that folder and it gives me an error. Please help, I'm just trying to extract the 

music from the Maiden Demo. You don't have any contact info so idk where else to ask

**Comment by Ekey** [comment]
In Command Prompt or you can use a [batch file](https://github.com/Ekey/REE.PAK.Tool/files/14167814/REE.Unpacker_Batch_file.zip)

Open it with notepad and set the full path to the PAK file
