### ISSUE TITLE
wwiseids.wid.2

### ISSUE THREAD

**Issue by Roachdaripper** [Ekey/REE.PAK.Tool#21]
Hello, this file is present in RE3R (Non-RT)'s list file, and it contains the bank IDs for all of the bnk and pck files, could this file be added to the other games' list files?

Thanks in advance

**Comment by Ekey** [comment]
Hi. Unfortunately, this file is not available in all games.

**Comment by Roachdaripper** [comment]
darn, do you know which games it is available in?

**Comment by Ekey** [comment]
> darn, do you know which games it is available in?

RE3, RE3 Demo, RE7, RE7 Kitchen Demo, RE Resistance, RE Re:Verse

**Comment by Roachdaripper** [comment]
alright thanks, shame this file isn't in other games
