### ISSUE TITLE
RE4 MAC？

### ISSUE THREAD

**Issue by shaoxuantoo** [Ekey/REE.PAK.Tool#22]
I have JP version by my JP app store，what should I do？

**Comment by Ekey** [comment]
Well, if you can upload it for me we can make a list (necessary files is main executable and pak files)

**Comment by shaoxuantoo** [comment]
> Well, if you can upload it for me we can make a list (necessary files is main executable and pak files)

Ok，just a moment

**Comment by shaoxuantoo** [comment]
https://drive.google.com/drive/folders/1vbJv60G3T1p-83z0S_6llewDszfzbF4S?usp=sharing

**Comment by shaoxuantoo** [comment]
https://drive.google.com/drive/folders/1AolRXJCadUwa3fyjdsP6G2dhRpgJf5kI?usp=sharing

**Comment by Ekey** [comment]
Thanks. Added list

**Comment by shaoxuantoo** [comment]
Ok,I'll delete this link,Thx
