### ISSUE TITLE
ui070101.msg.22 System.Collections.Generic.KeyNotFoundException: issue

### ISSUE THREAD

**Issue by LordElrond3** [Ekey/REE.PAK.Tool#23]
There is such an error for Dogma 2, it normally worked without any problems. When will a new msg update come out? Thank you in advance for your work.

**Comment by Ekey** [comment]
Are you talking about **REngine_Text-Tool** ?

**Comment by LordElrond3** [comment]
Sorry, I wrote in the wrong place, but msg tool causes problems in terms of import and export. Isn't there a tool other than msg tool that we can import and export msg.22 files with?

**Comment by Ekey** [comment]
> Sorry, I wrote in the wrong place, but msg tool causes problems in terms of import and export. Isn't there a tool other than msg tool that we can import and export msg.22 files with?

You can check gibbed project > https://github.com/gibbed/Gibbed.DragonsDogma2/tree/main/projects

**Comment by LordElrond3** [comment]
I'm a little new to these issues, I haven't seen a released version in the gibbed project. When I downloaded the -main folder, I only saw files with different file extensions. Why can't the msg tool import only the msg file named ui070101.msg.22? I can't figure out why.
