### ISSUE TITLE
I can't find where to run these commands

### ISSUE THREAD

**Issue by turkiet** [Ekey/REE.PAK.Tool#27]
I'm make to extract. In the main directory and in the "REE.Unpacker" directory
REE.Unpacker DENEME "TAP-WindowsNoEditor.pak" "cikti"
REE.Unpacker "DENEME" "TAP-WindowsNoEditor.pak" "cikti"
REE.Unpacker "DENEME" "E:\Diger Oyunlar\My Life Farm Vet\TAP\Content\Paks\TAP-WindowsNoEditor.pak" "E:\ue zımbırtıları\REE.PAK.Tool-main\cikti"
I've run commands like that, but there's no response.

**Comment by Ekey** [comment]
You can't extract cuz game My Life Farm on **Unreal Engine 4**. The list of supported games is on the main page of the project.
