### ISSUE TITLE
New to the area.

### ISSUE THREAD

**Issue by BaillieAlex** [Ekey/REE.PAK.Tool#28]
Hello, I'm new to the area and need some help. 

I have .net and VS code installed on my pc. How do I actually preform the unpacking?

I have read the "README" but still don't know where and how to excute (REE.Unpacker "TAG_LIST_FILE" "INPUT_PAK_FILE"). 

Also, could you give a example of (REE.FontsCryptor "INPUT_FONT_FILE" "OUTPUT_FONT_FILE")?

Sorry if I look dumb, I'm really new...

Thank you!

**Comment by BaillieAlex** [comment]
Follow up, 

I did check out the older issues, downloaded the batch file and specified my path as (REE.Unpacker MHR_PC_Release "E:\REE.PAK.Tool-main\REE.Unpacker\re_chunk_000.pak.patch_003.pak"). However when I run the batch file the cmd.exe opens but  nothing happans. 
I have attached two screenshots in case I didn't make it clear.
![1](https://github.com/Ekey/REE.PAK.Tool/assets/116459694/24598efd-f068-4c30-9461-80f5d71fb174)
![2](https://github.com/Ekey/REE.PAK.Tool/assets/116459694/eb87e245-8600-4662-8614-ac8475feda31)

Thank you

**Comment by BaillieAlex** [comment]
Follow up, 
I have the unpacker figured out from the older issues. Could you also send an executable packer file? 
Thank you!

**Comment by Ekey** [comment]
Hi, sorry for the long answer, too much main work!

[REE.Packer.zip](https://github.com/user-attachments/files/15992815/REE.Packer.zip)
