### ISSUE TITLE
Any chance for Capcom Fighting Collection?

### ISSUE THREAD

**Issue by 2meito** [Ekey/REE.PAK.Tool#29]
I'd be willing to send you a steam key if you need it.

**Comment by Ekey** [comment]
if you mean [this](https://store.steampowered.com/app/1685750/Capcom_Fighting_Collection/) game then it does not use the RE Engine

**Comment by 2meito** [comment]
Ah, I had no idea. Do you know if it's a new engine?

**Comment by Ekey** [comment]
> Ah, I had no idea. Do you know if it's a new engine?

No, it's a old **MT Framework**

**Comment by 2meito** [comment]
> > Ah, I had no idea. Do you know if it's a new engine?
> 
> No, this is the old **MT Framework**
Gotcha, thanks for letting me know.
