### ISSUE TITLE
Update RE2_PC_Release.list

### ISSUE THREAD

**Issue by Alexa2166** [Ekey/REE.PAK.Tool#3]
Hi, I'm a new modder working on a translation project for Resident Evil 2 Remake. I want to thank you for RE2_PC_Release.list because it really helped me to complete my mod. but i found 5 unknown msg.17 files. 2 files for the '98 costum dlc and 3 files one of which I think is the file for the ray tracing settings. So, I really hope that you will be willing to update the filepath list so that I can complete my translation mod project. anyways, great job guys.

**Comment by Ekey** [comment]
👍

**Comment by SkebbZ** [comment]
I've had reports from someone who accidentally used the RE3RT file list on the RE2RT install and got additional files, specifically the missing BulletShellUserData files I've been looking for. Know anything about this?

Folder: natives\stm\objectroot\prefab\shell\shell\entity\bullet
