### ISSUE TITLE
Unknown 

### ISSUE THREAD

**Issue by modz2014** [Ekey/REE.PAK.Tool#30]
hi im not sure but i don't get the native folder when trying to unpack the RE2 remake I don't see the native folder at all

**Comment by modz2014** [comment]
Also it does not extract all the files to mod the characters either

**Comment by Ekey** [comment]
Hi. Default or RT version?

**Comment by modz2014** [comment]
@Ekey i tired both

**Comment by Ekey** [comment]
Show me the command line you are using.
