### ISSUE TITLE
Bug? Useless if condition

### ISSUE THREAD

**Issue by eigeen** [Ekey/REE.PAK.Tool#36]
Position: https://github.com/Ekey/REE.PAK.Tool/blob/30b02f3f3fe4ef598d2152122f48dc947e069f01/REE.Unpacker/REE.Unpacker/FileSystem/Package/PakUnpack.cs#L82

`m_Header.bMajorVersion == 2 && m_Header.bMajorVersion == 4` always equal to `false`.

In addition, if not for insurance purposes, the `else if` can be merged with `else`, because `m_Header.bMinorVersion` was previously determined that can only be 0 or 1.

**Comment by Ekey** [comment]
This part of code is left over from early experiments ¯\_(ツ)_/¯
