### ISSUE TITLE
NPK.Tool

### ISSUE THREAD

**Issue by Niocas** [Ekey/REE.PAK.Tool#37]
Hey, sorry for trying to reach you this way; I couldn't find any other way to contact you.
I wanted to try my luck this way. I am currently trying to gather data for the Once Human
wiki like item data, weapon info, and textures. 

Once Human also uses the NetEase NeoX Game Engine and I unpacked the NPK files with the
neox_tools (https://github.com/MarcosVLl2/neox_tools). I started splitting all files by their file ending
and ended up assuming the item information have to be in the ".vis" files/archives. But there seems to
be no way to unpack them. Do you have any insights, if I am correct that those .vis files hold the information
I am looking for, and do you know how I could possibly get the data for the wiki?

Thanks a lot! Sorry for creating an issue here; the old repository was archived.

LA.NPK: https://github.com/Ekey/LA.NPK.Tool

In case you have discord my username is: wikilyapp
I would appreciate it a lot!

**Comment by Ekey** [comment]
Hi. As far as I remember, in this engine all information (like database) is stored in compiled python scripts, idk about other stuff.
