### ISSUE TITLE
Dead Rising Deluxe Remaster Filelist

### ISSUE THREAD

**Issue by Narayanna** [Ekey/REE.PAK.Tool#39]
Hello Ekey
Can you please make a filelist for Dead Rising Deluxe Remaster?
I packed all the file content of the game.

https://gofile.io/d/vO0qLr

**Comment by Ekey** [comment]
Hi. Already released.

**Comment by Narayanna** [comment]
That worked, you're really fast.
Thank you very much, Ekey. :)
