### ISSUE TITLE
I have RE2 remake and RE3 Remake Japanese Z editions.

### ISSUE THREAD

**Issue by Elliezrah** [Ekey/REE.PAK.Tool#4]
Hello,
I got those editions.
Thought i'd let you know because I saw the notice on the front page.

**Comment by Ekey** [comment]
Hello. Can you upload them? :)

**Comment by Elliezrah** [comment]
Where would you like me to upload them?

**Comment by Ekey** [comment]
> Where would you like me to upload them?

Google or Mega 👍 Thanks

**Comment by Elliezrah** [comment]
Didn't have enough space for Google or Mega.
Uploaded to Hugging Face instead.

https://huggingface.co/datasets/Elliezrah/RE2-Z-JP/tree/main

You might need an account to download.
Click on download icon beside RE2ZJP.

**Comment by Elliezrah** [comment]
I will do RE3 remake soon.

**Comment by Elliezrah** [comment]
Also, forgot to mention that those are Steam versions.

If you could send me some files to fix this mod for RT update it would be great.
https://www.nexusmods.com/residentevil22019/mods/137?tab=description
Or just copy of US edition. And see if I can fix this mod...

**Comment by Ekey** [comment]
> Didn't have enough space for Google or Mega. Uploaded to Hugging Face instead.
> 
> https://huggingface.co/datasets/Elliezrah/RE2-Z-JP/tree/main
> 
> You might need an account to download. Click on download icon beside RE2ZJP.

Thanks! It's RT or Non-RT version?

> If you could send me some files to fix this mod for RT update it would be great.

No ideas, but you can ask in [Modding Haven](https://discord.gg/moddinghaven) discord, maybe someone can help you with this.

**Comment by Elliezrah** [comment]
It's with the latest update (RT version).

Forget it about the modding fix, I took care of it.

Have you downloaded the files? I'm deleting it after you finished downloading it and move on to uploading RE3R.

**Comment by Ekey** [comment]
> Have you downloaded the files? I'm deleting it after you finished downloading it and move on to uploading RE3R.

Yep

**Comment by Elliezrah** [comment]
Ok, im going to upload the other one on sunday or monday. Bit tight on schedule at the moment

**Comment by Elliezrah** [comment]
https://huggingface.co/datasets/Elliezrah/RE3Z/tree/main

RE3Z is uploaded here

**Comment by Ekey** [comment]
> https://huggingface.co/datasets/Elliezrah/RE3Z/tree/main
> 
> RE3Z is uploaded here

Thanks, took it

**Comment by Elliezrah** [comment]
That's all I have. Hope it helped.

**Comment by Ekey** [comment]
> That's all I have. Hope it helped.

Sure, I'll take a look when I have more free time. Thanks again.
