### ISSUE TITLE
How to Run command and release .exe please

### ISSUE THREAD

**Issue by Shadowzj** [Ekey/REE.PAK.Tool#42]
How to Run command and release .exe please

I'm create bat file for run script  run.bat:
`**REE.Unpacker RE4_STM_Release "E:\Games\RESIDENT EVIL 4\re_chunk_000.pak.patch_001.pak" "D:\RE4_Unpacked"**`

but not work. 

relese REE.Unpacker to  .exe please

**Comment by Ekey** [comment]
[REE.Unpacker.zip](https://github.com/user-attachments/files/17604323/REE.Unpacker.zip)

Don't forget to copy Projects folder in the tool folder before use.
