### ISSUE TITLE
*.ttf support

### ISSUE THREAD

**Issue by matyalatte** [Ekey/REE.PAK.Tool#6]
Hi.
I noticed RE4 supports `*.ttf` files.
There is no change in the file format of `*.oft.1`.
But some decrypted files have `0x00000100` as magic.

**Comment by Ekey** [comment]
I don't have this game to check files, also Capcom blocking their games in my country.

**Comment by matyalatte** [comment]
I sent a oft file via discord.
matyamodding in Modding Haven

**Comment by Ekey** [comment]
I will check it when I have more free time

**Comment by Ekey** [comment]
So the magic 0x00000100 is the standard font and you can view it by default font viewer

![Screenshot_1](https://user-images.githubusercontent.com/1664144/235315194-87ca5770-32a6-4170-9814-0d594fbeb101.png)

No Issues here :)

**Comment by matyalatte** [comment]
Thanks for taking your time.
Yeah, oft2ttf will work.
But I meant your tool didn't support ttf2oft.
I tried to fix it yesterday,
and I found adding the following line to `Program.cs` seemed to fix.
`case 0x00000100: FontEncrypt.iDoIt(TFontsReader, m_DstFile); break;`

**Comment by Ekey** [comment]
Pushed. Anyway, I'll rewrite code to use the tool with commands -d, -e
