### ISSUE TITLE
RE Village update

### ISSUE THREAD

**Issue by Viuys** [Ekey/REE.PAK.Tool#7]
In the recent update (June 26th) capcom has changed the msg files paths. Could you update your .list file for RE8?

**Comment by r00t0s** [comment]
The previous paths was = natives/stm/message/gui/ui_hud.msg.17
The new is = natives/stm/message/gui/ui_hud.msg.33685777
The only what think what you need is replace 17 to 33685777
![Screenshot_1](https://github.com/Ekey/REE.PAK.Tool/assets/20927731/281a007c-1f86-487b-b4fa-15c61f2c0155)
[filenames.log](https://github.com/Ekey/REE.PAK.Tool/files/12123396/filenames.log)

**Comment by Ekey** [comment]
Done. Thanks :)
