### ISSUE TITLE
Ghost Trick project file?

### ISSUE THREAD

**Issue by CrazyMLC** [Ekey/REE.PAK.Tool#9]
Strangely enough, the new Ghost Trick remaster uses RE Engine. I'm interested in looking into its internals, but apparently a list of filenames is needed to extract the pak?

Could a list be made for the game, or it explained how to make my own list? Or just, let it extract files without defined names, just counting up?

**Comment by Ekey** [comment]
It is not necessary to have a list of names to research the files ;) Maybe I'll make a list as I have more free time.
